### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by K0rkunc** [KunYi/Quectel-Linux#1]
hi im try but 

root@orangepizero2:~/KernelDriver_GobiNet# make
ln -sf makefile Makefile
make ARCH=aarch64 CROSS_COMPILE= -C /lib/modules/4.9.318-sun50iw9/build M=/root/KernelDriver_GobiNet modules
make[1]: *** /lib/modules/4.9.318-sun50iw9/build: No such file or directory.  Stop.
make: *** [makefile:32: default] Error 2

**Comment by KunYi** [comment]
you need check your environments setting 

check 'lib/modules/4.9.318-sun50iw9/build' is your KDIR (linux header)
or assignment  correct path

verify on my host is passed
--------------------------

kunyi@mint: /tmp/Quectel-Linux/KernelDriver_GobiNet$ make
ln -sf makefile Makefile
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.15.0-73-generic/build M=/tmp/Quectel-Linux/KernelDriver_GobiNet modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-73-generic'
  CC [M]  /tmp/Quectel-Linux/KernelDriver_GobiNet/GobiUSBNet.o
  CC [M]  /tmp/Quectel-Linux/KernelDriver_GobiNet/QMIDevice.o
In file included from /tmp/Quectel-Linux/KernelDriver_GobiNet/QMI.c:72,
                 from /tmp/Quectel-Linux/KernelDriver_GobiNet/QMIDevice.c:103:
/tmp/Quectel-Linux/KernelDriver_GobiNet/QMIDevice.c: In function ‘IntCallback’:
/tmp/Quectel-Linux/KernelDriver_GobiNet/QMI.h:81:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
   81 |    if (quec_debug == 1)\
      |       ^
/tmp/Quectel-Linux/KernelDriver_GobiNet/QMIDevice.c:773:15: note: in expansion of macro ‘DBG’
  773 |               DBG( "resuming traffic due to CONNECTION_SPEED_CHANGE\n" );
      |               ^~~
/tmp/Quectel-Linux/KernelDriver_GobiNet/QMIDevice.c:776:7: note: here
  776 |       default:
      |       ^~~~~~~
  CC [M]  /tmp/Quectel-Linux/KernelDriver_GobiNet/QMI.o
  LD [M]  /tmp/Quectel-Linux/KernelDriver_GobiNet/GobiNet.o
  MODPOST /tmp/Quectel-Linux/KernelDriver_GobiNet/Module.symvers
  CC [M]  /tmp/Quectel-Linux/KernelDriver_GobiNet/GobiNet.mod.o
  LD [M]  /tmp/Quectel-Linux/KernelDriver_GobiNet/GobiNet.ko
  BTF [M] /tmp/Quectel-Linux/KernelDriver_GobiNet/GobiNet.ko
Skipping BTF generation for /tmp/Quectel-Linux/KernelDriver_GobiNet/GobiNet.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-73-generic'

---------------------------------------------------------------------------------------

ls  /lib/modules/5.15.0-73-generic/ -al
total 6480
drwxr-xr-x  6 root root    4096 May 31 12:53 .
drwxr-xr-x 14 root root    4096 May 31 12:52 ..
lrwxrwxrwx  1 root root      40 May 15 21:10 build -> /usr/src/linux-headers-5.15.0-73-generic
drwxr-xr-x  2 root root    4096 May 15 21:10 initrd

**Comment by K0rkunc** [comment]
checked /lib/modules/4.9.318-sun50iw9 got it but    build folders not found 

root@orangepizero2:~# ls /lib/modules/4.9.318-sun50iw9
kernel                     modules.builtin.bin  modules.softdep
modules.alias              modules.dep          modules.symbols
modules.alias.bin          modules.dep.bin      modules.symbols.bin
modules.builtin            modules.devname
modules.builtin.alias.bin  modules.order

**Comment by KunYi** [comment]
your need install linux headers first 
read [build  kernel modules](https://www.kernel.org/doc/Documentation/kbuild/modules.txt)
close the issues first
